workflows:
  zikafrica-ios-workflow:
    name: ZikAfrica iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      xcode: latest

    scripts:
      - name: Build ZikAfrica
        script: |
          xcodebuild clean build \
            -project ZikAfrica.xcodeproj \
            -scheme ZikAfrica \
            -destination 'generic/platform=iOS' \
            CODE_SIGNING_ALLOWED=NO
